### ISSUE TITLE
Focused buttons don't get highlighted

### ISSUE THREAD

**Issue by code-IM-perfect** [catppuccin/Kvantum#2]
I'm using macchito blue and the keyboard focused buttons don't get highlighted as you'd expect. if it's something that'd take time, just point me in the right category that controls it (I suspect its ItemView)

There's a ss of the issue
![Screenshot_86](https://user-images.githubusercontent.com/77197959/187063626-4b393887-4232-419d-ab04-12afba8a0f40.png)

here quit is in focus and I can change the focus via arrows but there's no visual indicator.

mouse focus works as expected
![Screenshot_87](https://user-images.githubusercontent.com/77197959/187063709-97ba204a-0723-4d4b-ac4e-82e65d7c367a.png)

**Comment by elkrien** [comment]
It's with the focus section but to be honest I have no luck to correct it. Will need more time to figure it out.

**Comment by code-IM-perfect** [comment]
@elkrien I figured it out, all you need is `combo_focus_rect=true` in the general section

also I needed to change the width and color of the focus lines to make them more visible.
![image](https://github.com/catppuccin/Kvantum/assets/77197959/e8bcbffa-523c-45ec-af3f-b85aec238245)

**Comment by code-IM-perfect** [comment]
@elkrien I am willing to fix this...but how did you generate these? like do I have to change stuff on all of the flavors manually? or is there a better approach?

**Comment by stenehall** [comment]
I'm not sure what the problem is. But assuming that `combo_focus_rect` is needed this would solve it https://github.com/catppuccin/Kvantum/compare/main...stenehall:add-combo-focus-rect?expand=1

I'm not sure how to test this do, since I've not seen the actual problem.

@code-IM-perfect could you test the updated theme and confirm if this works or not? Before I open a PR.

**Comment by code-IM-perfect** [comment]
@stenehall  actually the entry isn't enough...I also needed to change the focus element in the svg file that I have shown in the screenshot

**Comment by stenehall** [comment]
> @stenehall actually the entry isn't enough...I also needed to change the focus element in the svg file that I have shown in the screenshot

Right. I clearly failed to read your entire message. If you still have your changes I can generate the theme for it. If you don't prefer to create a PR yourself?

**Comment by code-IM-perfect** [comment]
@stenehall Sorry was short on time for a while, I made a PR that fixes it
