### ISSUE TITLE
Active button icon not visible

### ISSUE THREAD

**Issue by tfkhdyt** [catppuccin/Kvantum#3]
It's hard to differentiate between active button icons because button color and icon color is not contrast

Theme: Mocha Blue

![Screenshot_20221207_083501](https://user-images.githubusercontent.com/47195537/206066147-3f96f2a8-658c-4e4e-9102-98040cd13012.png)

![Screenshot_20221207_083728](https://user-images.githubusercontent.com/47195537/206066394-c9b69714-e3c8-4b06-b53f-e611b4c15453.png)

**Comment by she11sh0cked** [comment]
Also affects the Dolphin sidebar
![image](https://user-images.githubusercontent.com/22623152/221158038-bbdce7f9-64c1-47da-9663-238c3fab5dc4.png)

**Comment by vandrw** [comment]
It also affects the sub-prompts in Dolphin (triggered by pressing CTRL +C or CTRL + D):
![status_bar](https://github.com/catppuccin/Kvantum/assets/34933567/d05c6d50-deb7-4c08-9280-4bc2183d99d8)

Has anyone managed to fix this? I tried looking deeper into the Kvantum config, but I cannot pinpoint the setting that affects the highlighted panel text shown in my example, nor in the cases above.

**Comment by sgoudham** [comment]
Hey 👋, 

We haven't had active contributions to this repository in a long time so apologies for letting this issue go stale. Recently, #14 has been merged which should resolve the issues in Dolphin and in other areas too. 

I'm going to close this issue given how long its been and would encourage anyone from this issue to raise a new issue going forwards if they still exist after trying out #14.

Thanks!
